### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement conda-package-handling==1.7.2

### ISSUE THREAD

**Issue by arasopraza** [gitfarhan/chat_analytics#1]
Followed the setup on README and I got this error:
![image](https://user-images.githubusercontent.com/34035232/99185905-59737200-277f-11eb-8998-1b37819f80d0.png)

**Comment by ffadilaputra** [comment]
we only need 3 dependencies to run this project, so update your requirements.txt to 

```
matplotlib==3.1.3
pandas==1.1.3
click==7.1.2
```
my python version : 3.8.5

and it works to me ✌🏻

cmiiw

**Comment by arasopraza** [comment]
> we only need 3 dependencies to run this project, so update your requirements.txt to
> 
> ```
> matplotlib==3.1.3
> pandas==1.1.3
> click==7.1.2
> ```
> 
> my python version : 3.8.5
> 
> and it works to me ✌🏻
> 
> cmiiw

btw i using python version : 3.9.0

**Comment by ffadilaputra** [comment]
i think its ok with that version, just try update the requirements.txt
